# Generated by Django 5.0.4 on 2024-04-17 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('ced_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=20)),
                ('correo_client', models.CharField(max_length=30)),
                ('contraseña_client', models.CharField(max_length=128)),
                ('tel_client', models.CharField(max_length=10)),
                ('direc_client', models.CharField(max_length=30)),
                ('ciudad_client', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_ced_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='factura_ensalda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamaño', models.CharField(max_length=10)),
                ('FK_ensalada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ensaladas')),
                ('FK_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.factura')),
            ],
        ),
        migrations.CreateModel(
            name='putuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_estrellas', models.IntegerField()),
                ('comentario', models.CharField(max_length=50)),
                ('FK_ced_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_recla', models.CharField(max_length=50)),
                ('foto_reclamo', models.ImageField(upload_to='reclamos/')),
                ('FK_ced_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cliente')),
            ],
        ),
    ]
