# Generated by Django 5.0.4 on 2024-05-10 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_factura_total_factura_ensalda_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamo',
            name='fecha_reclamo',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
