# Generated by Django 5.0.4 on 2024-05-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_user_alter_factura_fk_ced_client_delete_putuacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
