# Generated by Django 5.0.4 on 2024-05-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_factura_options_remove_factura_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='apell_client',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='factura',
            name='nom_client',
            field=models.CharField(default='', max_length=30),
        ),
    ]
