# Generated by Django 5.0.4 on 2024-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_factura_apell_client_factura_nom_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
