# Generated by Django 5.0.4 on 2024-05-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_factura_created_alter_factura_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='preparada',
            field=models.BooleanField(default=False),
        ),
    ]
