# Generated by Django 5.0.4 on 2024-04-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ensaladas',
            fields=[
                ('ID_ensalada', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_ensalada', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ingrediente',
            fields=[
                ('ID_ing', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_ing', models.CharField(max_length=20)),
                ('cant_gramos', models.FloatField()),
                ('cant_min', models.FloatField()),
                ('precio_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prov', models.CharField(max_length=20)),
                ('correo_prov', models.CharField(max_length=30)),
                ('tel_prov', models.CharField(max_length=10)),
                ('ciudad_prov', models.CharField(max_length=20)),
                ('desc_prov', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='product_prov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_prov', models.FloatField()),
                ('FK_ID_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ingrediente')),
                ('FK_nit_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_ID_ensalada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ensaladas')),
                ('FK_ID_ing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ingrediente')),
            ],
        ),
    ]
