# Generated by Django 5.0.4 on 2024-05-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_ingrediente_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensaladas',
            options={'verbose_name': 'Ensadala', 'verbose_name_plural': 'Ensadalas'},
        ),
        migrations.AlterModelOptions(
            name='recetas',
            options={'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
        migrations.AddField(
            model_name='ensaladas',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='cant_min',
            field=models.FloatField(verbose_name='Cantidad minima (gramos)'),
        ),
    ]
