# Generated by Django 5.0.4 on 2024-05-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_ensaladas_options_alter_recetas_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensaladas',
            name='categoria',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='FK_ID_ensalada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ensaladas', verbose_name='Ensalada'),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='FK_ID_ing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.ingrediente', verbose_name='Ingrediente'),
        ),
    ]
