# Generated by Django 5.0.4 on 2024-05-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0006_ensaladas_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='precio_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
