# Generated by Django 5.0.4 on 2024-05-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0007_alter_ingrediente_precio_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.CharField(default='', max_length=30),
        ),
    ]
