# Generated by Django 5.0.4 on 2024-04-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0002_delete_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='hola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hola', models.CharField(max_length=10)),
            ],
        ),
    ]
