# Generated by Django 5.0.4 on 2024-04-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0003_hola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hola',
        ),
        migrations.DeleteModel(
            name='rol',
        ),
    ]
