# Generated by Django 5.0.4 on 2024-04-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerente', '0004_delete_hola_delete_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Rol', models.CharField(max_length=20)),
            ],
        ),
    ]
