# Generated by Django 5.0.4 on 2024-04-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0008_empleado_is_active_empleado_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='contrasena_emp',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
