# Generated by Django 5.0.4 on 2024-04-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0009_alter_empleado_contrasena_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='contrasena_emp',
            new_name='contrasena',
        ),
    ]
