# Generated by Django 5.0.4 on 2024-05-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerente', '0010_rename_contrasena_emp_empleado_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='password',
        ),
    ]
